config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  resources :bands
  resources :albums

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :band
  validates :band, presence: true
  validates :name, presence: true
end

app/models/band.rb
class Band < ActiveRecord::Base
  has_many :albums, dependent: :destroy
  validates :name,  presence: true, 
                    uniqueness: true,
                    case_sensitive: false
                    
  def get_name
    self.name
  end
  
  def self.get_name_by_id the_id
    Band.find(params[the_id])
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    @album = Album.new
    @bands = Band.all
  end

  def create
    @album = Album.new(album_params)
    @bands = Band.all
    
    if @album.save
      flash[:success] = "Album has been added."
      redirect_to @album
    else
      render 'new'
    end
  end
  
  def show
    @album = Album.find(params[:id])
    @band = Band.find(@album.band_id)
  end
  
  def index
    @albums = Album.all
  end
  
  def edit
    @album = Album.find(params[:id])
    @bands = Band.all
  end

  def update
    @album = Album.find(params[:id])
    if @album.update_attributes(album_params)
      flash[:success] = "Album updated"
      redirect_to @album
    else
      render 'edit'
    end
  end
  
  def destroy
    Album.find(params[:id]).destroy
    flash[:success] = "Album deleted"
    redirect_to albums_path
  end
  
  private

    def album_params
      params.require(:album).permit(:name, :info, :photo, :band_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      flash[:success] = "Band has been added."
      redirect_to @band
    else
      render 'new'
    end
  end
  
  def show
    @band = Band.find(params[:id])
    @albums = @band.albums
  end
  
  def index
    @bands = Band.all
  end
  
  def edit
    @band = Band.find(params[:id])
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(band_params)
      flash[:success] = "Band updated"
      redirect_to @band
    else
      render 'edit'
    end
  end
  
  def destroy
    Band.find(params[:id]).destroy
    flash[:success] = "Band deleted"
    redirect_to bands_path
  end
  
  private

    def band_params
      params.require(:band).permit(:name, :biography, :photo)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @bands = Band.all
  end

  def about
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Discographica"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/albums/edit.html.erb
<h1>Edit album: <%= @album.name %></h1>
<div class="signup-form">
  
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@album.errors.count, "error") %>:
      </div>
      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form_for(@album) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    
    <%= f.label :band %>
    <%= f.collection_select(:band_id, @bands, :id, :get_name, prompt: true) %>
  
    <%= f.label :photo %>
    <%= f.text_field :photo %>
  
    <%= f.submit "Edit", class: "btn" %>
  <% end %>
  
  <%= link_to '<div class="btn">Delete album</div>'.html_safe, @album, method: :delete, data: { confirm: "You sure?" } %>
</div>

app/views/albums/index.html.erb
<h1>Albums</h1>
<%= link_to '<div class="btn">Add a new album</div>'.html_safe, new_album_path %>
<ul class="band-list">
  <% @albums.each do |album| %>
    <li>
      <%= link_to album.name, album %>
    </li>
  <% end %>
</ul>

app/views/albums/new.html.erb
<h1>New album</h1>
<div class="signup-form">
  
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@album.errors.count, "error") %>:
      </div>
      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form_for(@album) do |f| %>
  
    <%= f.label :name %>
    <%= f.text_field :name %>
    
    <%= f.label :band %>
    <%= f.collection_select(:band_id, @bands, :id, :get_name, prompt: true) %>
  
    <%= f.label :photo %>
    <%= f.text_field :photo %>
  
    <%= f.submit "Create album", class: "btn" %>
  <% end %>
</div>

app/views/albums/show.html.erb
<h1><%= @album.name %></h1>
<h3><%= link_to @band.name, @band %></h3
<%= image_tag(@album.photo, class: 'band-focus-image') %>
<% if @album.info != "" %>
  <h2>About</h2>
  <p><%= @album.info %></p>
<% end %>
<%= link_to '<div class="btn">Edit album</div>'.html_safe, edit_album_path %>

app/views/bands/edit.html.erb
<h1>Edit band: <%= @band.name %></h1>
<div class="signup-form">
  
  <% if @band.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@band.errors.count, "error") %>:
      </div>
      <ul>
      <% @band.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form_for(@band) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
  
    <%= f.label :biography %>
    <%= f.text_area :biography %>
  
    <%= f.label :photo %>
    <%= f.text_field :photo %>
  
    <%= f.submit "Edit", class: "btn" %>
  <% end %>
  
  <%= link_to '<div class="btn">Delete band</div>'.html_safe, @band, method: :delete, data: { confirm: "You sure?" } %>
</div>

app/views/bands/index.html.erb
<h1>Bands</h1>
<%= link_to '<div class="btn">Add a new band</div>'.html_safe, new_band_path %>
<ul class="band-list">
  <% @bands.each do |band| %>
    <li>
      <%= link_to band.name, band %>
    </li>
  <% end %>
</ul>

app/views/bands/new.html.erb
<h1>New band</h1>
<div class="signup-form">
  
  <% if @band.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@band.errors.count, "error") %>:
      </div>
      <ul>
      <% @band.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form_for(@band) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
  
    <%= f.label :biography %>
    <%= f.text_area :biography %>
  
    <%= f.label :photo %>
    <%= f.text_field :photo %>
  
    <%= f.submit "Create band", class: "btn" %>
  <% end %>
</div>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<%= image_tag(@band.photo, class: 'band-focus-image') %>

<% if @band.biography != "" %>
  <h2>Biography</h2>
  <p><%= @band.biography %></p>
<% end %>

<% if @albums.length > 0 %>
  <h2>Albums</h2>
  <ul class="band-list">
  <% @albums.each do |album| %>
    <li>
      <%= link_to album.name, album %>
    </li>
  <% end %>
  </ul>
<% end %>

<%= link_to '<div class="btn">Edit band</div>'.html_safe, edit_band_path %>

app/views/layouts/_header.html.erb
<header>
  <%= link_to image_tag("logo.png"), root_path %>
  <nav>
    <ul>
      <%= link_to '<li>Bands</li>'.html_safe, bands_path %>
      <%= link_to '<li>Albums</li>'.html_safe, albums_path %>
      <%= link_to '<li>About</li>'.html_safe, about_path %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %> | Discographica</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,300,300italic,700,700italic' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
  <![endif]-->
</head>
<body>
  
  <%= render 'layouts/header' %>
  
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>

</body>
</html>

app/views/static_pages/about.html.erb
<%= provide(:title, "About") %>
<h1>About</h1>
<p><strong>Discograpica</strong> is a simple discography application created using Ruby on Rails. It may not be useful, but it's a start.</p>

app/views/static_pages/home.html.erb
<p>Welcome to <strong>Discographica!</strong></p>
<h2>Bands</h2>
<ul class="band-list">
  <% @bands.each do |band| %>
    <li>
      <%= link_to band.name, band %>
    </li>
  <% end %>
</ul>